server:
  servlet:
    context-path: /OnlineAuction
spring:
  jackson:
    default-property-inclusion: non_empty
    serialization.FAIL_ON_EMPTY_BEANS: false
  application:
    name: OnlineAuction
  flyway:
    enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Root@12345
    url: jdbc:mysql://localhost:3306/ONLINE_AUCTION?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

